# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  print-hello:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - run: echo hello
  print-world:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - run: echo world
  save_hello_world_output:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - run: echo "This is a sample output text" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  my_job:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - print_pipeline_id

# Orchestrate jobs using workflows
workflows:
  welcome:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - my_job
